#!/usr/bin/env perl
# fasta2tsv
# Johan Nylander
local $/ = '>';
while(<>) {
    chomp;
    next if($_ eq '');
    my ($h, @S) = split /\n/;
    my $t = join('', @S);
    my (@m) = split //, $t;
    my $s = join("\t", @m);
    print STDOUT "$h\t$s\n" unless (!$h);
}
